export const LENDERS = [
  {
    name: 'Camco',
    restrictions: 'No manufacturer restrictions',
    types: {
      'Touring Caravan': {
        maxAge: '20yr end of term',
        maxMileage: null,
        minTerm: '36 months',
        maxTerm: '120 months',
        minLoan: '£5,000',
        maxLoan: '£100,000',
        minDeposit: '5%',
        notes: null,
      },
      'Motorhome': {
        maxAge: '20yr end of term',
        maxMileage: '120,000',
        minTerm: '36 months',
        maxTerm: '120 months',
        minLoan: '£5,000 (prefer £10k+)',
        maxLoan: '£100,000',
        minDeposit: '5%',
        notes: null,
      },
      'Campervan': {
        maxAge: '20yr end of term',
        maxMileage: '120,000',
        minTerm: '36 months',
        maxTerm: '120 months',
        minLoan: '£5,000',
        maxLoan: '£100,000',
        minDeposit: '5%',
        notes: null,
      },
    },
  },
  {
    name: 'BNP Paribas',
    restrictions: 'No manufacturer restrictions',
    types: {
      'Motorhome': {
        maxAge: '15yr start / 20yr end',
        maxMileage: '75,000',
        minTerm: '24 months',
        maxTerm: '180 months (assets under 2yr old)',
        minLoan: '£5,000',
        maxLoan: '£150,000',
        minDeposit: '£2,500',
        notes: null,
      },
      'Campervan': {
        maxAge: '15yr start / 20yr end',
        maxMileage: '75,000',
        minTerm: '24 months',
        maxTerm: '180 months (assets under 2yr old)',
        minLoan: '£5,000',
        maxLoan: '£150,000',
        minDeposit: '£2,500',
        notes: null,
      },
    },
  },
  {
    name: 'Paragon',
    restrictions: 'No restrictions on caravans/motorhomes. Campervans: approved converters list only.',
    types: {
      'Touring Caravan': {
        maxAge: '20yr end of term',
        maxMileage: null,
        minTerm: '24 months',
        maxTerm: '120 months',
        minLoan: '£5,000',
        maxLoan: 'Homeowners £150k / Tenants £50k',
        minDeposit: null,
        notes: null,
      },
      'Motorhome': {
        maxAge: '20yr end of term',
        maxMileage: '120,000',
        minTerm: '24 months',
        maxTerm: '180 months',
        minLoan: '£10,000',
        maxLoan: '£150,000',
        minDeposit: null,
        notes: null,
      },
      'Campervan': {
        maxAge: '20yr end of term',
        maxMileage: '120,000',
        minTerm: '24 months',
        maxTerm: '120 months',
        minLoan: null,
        maxLoan: '£150,000',
        minDeposit: null,
        notes: null,
        approvedConverters: [
          'Autocraft Motor Caravans', 'AVT Campers', 'Bath VW Campers', 'Bilbos Campervans',
          'Bodans Camper Conversions', 'Bridgewater Campers', 'Calder Campers',
          'Cambridge Campervans Ltd', 'Camper King', 'Camper Monster', 'Camperversions',
          'Crowther Lodge', 'Custom Design Campervans', 'D.H. MOTORS Ltd t/a Landseer Leisure',
          'Danbury Campervans', 'Denby Campervans', 'Dormobile Ltd',
          'GM COACHWORK Ltd t/a Ventura', 'Hillside Leisure', 'Leisuredrive Campervans Ltd',
          'Mini Campers North East', 'Needingworth Campers Ltd', 'Platinum Wave Automotive',
          'Redline Conversions Ltd t/a Redline Campers', 'Rising Sun Campers',
          'Rolling Homes Camper Ltd', 'Southlands Motor Company Ltd', 'Spinney',
          'The Campervan Factory', 'The Wee Camper Company', 'Tiger Moth Campers',
          'UKPOPTOPS Ltd t/a All Season Leisure', 'Ultimate Camper Sales', 'Van Haven Ltd',
          'Vanworx', 'Wildax', 'Wildtracks Campervans', 'Woodstock Campers',
        ],
      },
    },
  },
  {
    name: 'CA Bank',
    restrictions: 'No manufacturer restrictions',
    types: {
      'Touring Caravan': {
        maxAge: '17yr end of term',
        maxMileage: null,
        minTerm: null,
        maxTerm: '150 months',
        minLoan: null,
        maxLoan: null,
        minDeposit: '0%',
        notes: null,
      },
      'Motorhome': {
        maxAge: '17yr end of term',
        maxMileage: '99,999',
        minTerm: null,
        maxTerm: '150 months',
        minLoan: null,
        maxLoan: null,
        minDeposit: '0%',
        notes: null,
      },
      'Campervan': {
        maxAge: '17yr end of term',
        maxMileage: '99,999',
        minTerm: null,
        maxTerm: '150 months',
        minLoan: null,
        maxLoan: null,
        minDeposit: '0%',
        notes: null,
      },
    },
  },
  {
    name: 'Close Brothers',
    restrictions: 'No manufacturer restrictions',
    types: {
      'Touring Caravan': {
        maxAge: '15yr end of term',
        maxMileage: null,
        minTerm: '24 months',
        maxTerm: '120 months',
        minLoan: null,
        maxLoan: '£200,000',
        minDeposit: '10%',
        notes: 'Prefer 48m+ for commission',
      },
      'Motorhome': {
        maxAge: '15yr end of term',
        maxMileage: '120,000',
        minTerm: '24 months',
        maxTerm: '120 months',
        minLoan: null,
        maxLoan: '£200,000',
        minDeposit: '10%',
        notes: 'Prefer 48m+ for commission',
      },
      'Campervan': {
        maxAge: '15yr end of term',
        maxMileage: '130,000',
        minTerm: '24 months',
        maxTerm: '60 months (120m if OEM)',
        minLoan: null,
        maxLoan: '£200,000',
        minDeposit: '30%',
        notes: 'Prefer 48m+ for commission',
      },
    },
  },
];
